config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/import'
  resources :users do
  	collection { post :import}
  end

  root to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	require 'csv'
	validates :name, :email, :number, presence: true
													
	def self.import(file)
					CSV.foreach(file.path, { encoding: "UTF-8", headers: true, header_converters: :symbol, converters: :all}) do |row|
			User.create! row.to_hash
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def redirect(url, text)
  	redirect_to url, notice: text
  end

  def index
  	@users = User.all
  end

  def import
  	if params[:file]
  		User.import(params[:file])
  		redirect(root_url, "Activity Data imported!")	
  	else
  		redirect(root_url, "Please upload a CSV file")
  	end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUpload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= flash[:notice] %>
<table>
	<thead>
		<th>User_Name</th>
		<th>User_Email</th>
		<th>Number</th>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr>
			<!-- 	<td><%= user.user %></td> -->
				<td><%= user.name %></td>
				<td><%= user.email %></td>
				<td><%= user.number %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<div>
	<h4> Import that data! </h4>
		<%= form_tag import_users_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Import CSV" %>
		<% end %> 
</div>